# Generated by Django 4.2.5 on 2023-09-18 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('f_name', models.CharField(max_length=255)),
                ('l_name', models.CharField(max_length=255)),
                ('fatherName', models.CharField(max_length=255)),
                ('motherName', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1)),
                ('phoneNumber', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BankDatails',
            fields=[
                ('accountNumber', models.CharField(max_length=255)),
                ('bankName', models.CharField(max_length=255)),
                ('bankIfsc', models.CharField(max_length=255)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dashboard.user')),
            ],
        ),
        migrations.CreateModel(
            name='FormStatus',
            fields=[
                ('status', models.CharField(choices=[('F', 'Unverified'), ('T', 'Verified'), ('P', 'Pending')], default='F', max_length=1)),
                ('lastUpdate', models.DateField(auto_now=True)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dashboard.user')),
            ],
        ),
    ]
